# -*- coding: utf-8 -*-
"""app.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1grYcSc3VRiAzOkM4arsstfekgQJ27z5x
"""

import streamlit as st

st.title("Kalkulator Sederhana")

angka1 = st.number_input("Masukkan angka pertama")
angka2 = st.number_input("Masukkan angka kedua")

if st.button("Hitung"):
    hasil = angka1 + angka2
    st.write("Hasil:", hasil)

